export const metadata = {
	title: "Hello from LuttAPI",
	description: "Generated by LuttAPI",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function Home() {
	return (
		<>Hi</>
	);
}